version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - code_recipes_mongodb:/data/db
    restart: unless-stopped
    container_name: mongo-db
  nginx:
    restart: always
    build:
        dockerfile: Dockerfile
        context: ./nginx
    volumes:
        - ./app/shared:/files
    ports:
        - '80:80'
        - '443:443'
    container_name: nginx
  server:
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    image: nodejs
    working_dir: /app
    container_name: server
    restart: unless-stopped
    env_file: 
      - ./.env
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
  # client:
  #   container_name: client
  #   build: 
  #     context: ./client
  #     dockerfile: Dockerfile
  #   volumes:
  #     - './client/src:/app'
  #     - '/app/node_modules'
  #   ports:
  #     - 3001:3001
  #   env_file: 
  #     - ./client/.env
  #   stdin_open: true
volumes:
  code_recipes_mongodb:
     