apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  # Ingress rules - base on path prefix send the request to the backend or the client app
  rules:
    - host: code-recipes.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: code-recipes-service
                port:
                  number: 4000
          - path: /?(.*)
            pathType: Prefix
            backend:
              service: 
                name: code-recipes-client-service
                port:
                  number: 3000