FROM node

# Create app directory
WORKDIR /usr/src/app

#RUN mkdir ~/.ssh && ln -s /run/secrets/host_ssh_key ~/.ssh/id_rsa

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

# build the app which uses es6 syntax
RUN npm run build

EXPOSE 3000
CMD [ "npm", "run", "start" ]